# Generated by Django 4.2.4 on 2023-08-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yookassa_id", models.CharField(max_length=100)),
                ("chat_id", models.CharField(max_length=100)),
                ("order_status", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payment_status", models.CharField(max_length=100)),
                (
                    "cooking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "order_content",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "total_price",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fiscal_check_sent", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "second_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("comment", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "refund_reason",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
    ]
